# SPDX-FileCopyrightText: 2023-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT
name: Release
on: workflow_dispatch

jobs:
  npm-registry:
    name: 'Npm registry'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: npm registry
    steps:
      - name: Conventional nextcloud npm release
        uses: ChristophWurst/conventional-nextcloud-npm-release@c2bd906c9bd92b278866d21b74459bdd4f2a4131 # v1.1.0
        with:
          github-token: ${{ secrets.RELEASE_PAT }}
          npm-token: ${{ secrets.NPM_TOKEN }}
